APP_NAME = "BandoriPet"
APP_VERSION = "3.0.9"

APP_REPOSITORY = "HELPMEEADICE/BANDORI-PET-REV"
APP_REPO_URL = f"https://github.com/{APP_REPOSITORY}"
APP_LICENSE_URL = f"{APP_REPO_URL}/blob/main/LICENSE"
APP_QQ_GROUP_URL = "https://qm.qq.com/q/VJMrn5EkWQ"

MAIN_EXECUTABLE = "BandoriPet.exe"
