; Inno Setup script for BandoriPet
; Generated by setup.py - do not edit manually

#define MyAppName "{APP_NAME}"
#define MyAppVersion "{APP_VERSION}"
#define MyAppPublisher "BandoriPet"
#define MyAppURL "{APP_REPO_URL}"
#define MyAppExeName "BandoriPet.exe"

[Setup]
AppId={APP_ID}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\BandoriPet
DefaultGroupName=BandoriPet
LicenseFile={LICENSE_FILE}
OutputDir={OUTPUT_DIR}
OutputBaseFilename={OUTPUT_FILENAME}
SetupIconFile={ICON_FILE}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\BandoriPet.exe
VersionInfoVersion={APP_VERSION}.0
VersionInfoCompany=BandoriPet
VersionInfoDescription=Bandori Desktop Pet
VersionInfoCopyright=Copyright (c) BandoriPet

[Languages]
{LANGUAGE_ENTRIES}

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "autostart"; Description: "Start with Windows"; GroupDescription: "Other:"; Flags: unchecked

[Files]
Source: "{BUILD_DIR}\*"; DestDir: "{app}"; Excludes: "config.json,data.db,data.db-shm,data.db-wal"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\BandoriPet"; Filename: "{app}\BandoriPet.exe"
Name: "{group}\{cm:UninstallProgram,BandoriPet}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\BandoriPet"; Filename: "{app}\BandoriPet.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\BandoriPet"; Filename: "{app}\BandoriPet.exe"; Tasks: quicklaunchicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "BandoriPet"; ValueData: """{app}\BandoriPet.exe"""; Tasks: autostart; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\BandoriPet"; ValueType: string; ValueName: "InstallerType"; ValueData: "inno"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\BandoriPet"; ValueType: string; ValueName: "InstallDir"; ValueData: "{app}"; Flags: uninsdeletekey

[Run]
Filename: "{app}\BandoriPet.exe"; Description: "{cm:LaunchProgram,BandoriPet}"; Flags: nowait postinstall skipifsilent
